### PR TITLE
feat: treat typescript as comments

### PR DESCRIPTION
**Pull request by load1n9**

### CODE REVIEW

**Review by aapoalas — CHANGES_REQUESTED** [review]
This should definitely be a build flag.

**Comment by load1n9** [comment]
cli flag?

**Comment by aapoalas** [comment]
A cargo feature.

**Comment by eliassjogreen** [comment]
Once https://github.com/tc39/proposal-type-annotations is finalized this will basically be the implementation but until then I agree that it should be behind a flag.

**Pull request closed without merging**
