### PR TITLE
feat(vm): Handle script data on the heap

### PR DESCRIPTION
**Pull request by aapoalas**
Built on top of #343.

Note: MIRI gives this the green light with (a good number of) `cargo test` tests cases. I didn't run all of them due to lack of time.

### CODE REVIEW

**Comment by aapoalas** [comment]
@andreubotella Main question: Looking at this, would you prefer that scripts actually refer to an `EvalSource` instead of holding the equivalent data internally?

**Comment by andreubotella** [comment]
> @andreubotella Main question: Looking at this, would you prefer that scripts actually refer to an `EvalSource` (then renamed to eg. `SourceCode`) instead of holding the equivalent data internally?

I haven't had the chance to look at all of this PR and #343, but yes, that seems like better code organization.

**Comment by aapoalas** [comment]
> I haven't had the chance to look at all of this PR and #343, but yes, that seems like better code organization.

The only thing that makes me sad about that is that then each script always creates two "heap objects", when it only really needs to create one. So there's a bit more tracing and sweeping to be done.

But, scripts are rare things in general so you're right: The code organization is way better.

**Comment by aapoalas** [comment]
Subsumed by the original #343

**Pull request closed without merging**
