### PR TITLE
build: add `justfile`

### PR DESCRIPTION
**Pull request by DonIsaac**
## What This PR Does

Adds a [justfile](https://github.com/casey/just?tab=readme-ov-file#just) with some shortcuts of common tasks. I've only added a few for now.

### CODE REVIEW

**Comment by aapoalas** [comment]
Thank you for the PR. Documenting these commands is _very good_ and I'm sorry you (probably) had to figure them out on your own.

That being said, what do you think about moving these to the `CONTRIBUTING.md` file instead of adding a `justfile`? I've personally never heard of `just` and I'm not sure any other active contributors are using it either; this would basically be a file by you, for you, and you alone at least for now.

**Comment by eliassjogreen** [comment]
I have to agree with @aapoalas that documenting these commands are very good, but should probably not be done with a `justfile`. I would probably not be in favor of these kinds of shortcuts even if they were done with `make` or something modern like `task` or `just`. But adding a section about common commands to the `CONTRIBUTING.md` would be very useful, I remember the pain of digging through the code before I figured out how to run (and update) the tests. 😅

**Comment by DonIsaac** [comment]
Documentation would certainly be useful. Do you guys not get tired of writing all those words all the time? I personally find task runners quite helpful.

**Comment by aapoalas** [comment]
> Do you guys not get tired of writing all those words all the time? I personally find task runners quite helpful.

I personally use shell Ctrl+R search and Up key to jump to the latest command that starts with whatever I've filled in.

So eg. `c` + Up a few times usually gives me what I want :)

**Comment by DonIsaac** [comment]
Makes sense. This behavior is quite annoying when using zsh with  multiple terminal windows open. This is, however, a me problem and if nobody else would find this useful we should close this PR.

**Pull request closed without merging**
