### PR TITLE
chore: replace cpu flag with fun clippy command

### PR DESCRIPTION
**Pull request by load1n9**

### CODE REVIEW

**Comment by eliassjogreen** [comment]
Why??? 😭

**Comment by aapoalas** [comment]
Mm, I don't quite understand what this does. Can you explain a bit?

**Comment by load1n9** [comment]
@eliassjogreen have clippy while we figure out what flags we want

**Comment by eliassjogreen** [comment]
Most likely we don't want any flags, and if we want any flags it's probably the one we have currently. So I say we keep it this way. Any possible build options we wan't to tweak we can do in the cargo profiles. E.g. opt-level, LTO, etc.

**Comment by MierenManz** [comment]
Do we currently provide builds? Or is everything build by the user?

Cuz we nee to remove the native cpu flag when providing builds because older systems may not support the features our build cpu does support

**Comment by eliassjogreen** [comment]
No, we don't yet provide pre-built executables. Maybe if we should start distributing C-bindings and a pre-built dynamically linked libnova? But the nova cli is mainly for debugging purposes so I don't see any reason to distribute that.

**Pull request closed without merging**
