### PR TITLE
chore: bump test262

### PR DESCRIPTION
**Pull request by eliassjogreen**
📉📉📉

### CODE REVIEW

**Review by aapoalas — CHANGES_REQUESTED** [review]
Some tests pass :)

**Comment by eliassjogreen** [comment]
Those two tests always fail locally for me for some reason 🤔? I usually just edit them out manually. I am gone for the weekend now, so if you (or my assistant @load1n9) could edit them out for me that would be appreciated 😊

**Comment by aapoalas** [comment]
I'll fix it.

**Comment by aapoalas** [comment]
Thank you <3

**Review by aapoalas — APPROVED** [review]

**Pull request merged**
