### PR TITLE
chore: Add license

### PR DESCRIPTION
**Pull request by aapoalas**
This PR finally adds a license, the MPLv2.0. This license has a few nice properties:
1. It's copyleft, but weak. This is very acceptable to companies but it does require any modifications to also be MPL2 or GPL, so this is not a "take and make it all proprietary" license.
2. It has a builtin contributor license agreement (hence why everyone's a reviewer).
3. It has a builtin patent troll protection.

### CODE REVIEW

**Comment by aapoalas** [comment]
@lino-levan & @load1n9 I can't add you as reviewers for some reason but you also have commits, so an approval from you would also be nice :)

**Comment by load1n9** [comment]
LGTM

**Review by eliassjogreen — APPROVED** [review]

**Review by sno2 — APPROVED** [review]

**Review by andreubotella — APPROVED** [review]
LGTM.

Btw, we'd also need to make sure vimirage is okay with this change of license, which might be hard since it seems they deleted their Github and Discord accounts. Does anyone have any way of contacting them?

**Comment by sno2** [comment]
> Btw, we'd also need to make sure vimirage is okay with this change of license, which might be hard since it seems they deleted their Github and Discord accounts. Does anyone have any way of contacting them?

I don't believe any of their contributions were ever merged.

image

**Comment by andreubotella** [comment]
> I don't believe any of their contributions were ever merged.

Yes they were: #49, #51, #52, #72. They also proposed changes that were accepted in PRs #50, #53 and #63, although those might not count as significant for copyright purposes.

**Comment by sno2** [comment]
Oh, thank you for checking. My bad.

**Review by lino-levan — APPROVED** [review]
LGTM

**Review by MierenManz — APPROVED** [review]
Lgtm

**Comment by sno2** [comment]
Phosra consented to the licensing.

**Pull request merged**
